// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: carsensor.proto

package carsensorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Car       int32   `protobuf:"varint,1,opt,name=car,proto3" json:"car,omitempty"`
	Route     int32   `protobuf:"varint,2,opt,name=route,proto3" json:"route,omitempty"`
	Latitude  float32 `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *SendPointRequest) Reset() {
	*x = SendPointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carsensor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPointRequest) ProtoMessage() {}

func (x *SendPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carsensor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPointRequest.ProtoReflect.Descriptor instead.
func (*SendPointRequest) Descriptor() ([]byte, []int) {
	return file_carsensor_proto_rawDescGZIP(), []int{0}
}

func (x *SendPointRequest) GetCar() int32 {
	if x != nil {
		return x.Car
	}
	return 0
}

func (x *SendPointRequest) GetRoute() int32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *SendPointRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SendPointRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type SendPointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Route  int32 `protobuf:"varint,1,opt,name=route,proto3" json:"route,omitempty"`
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SendPointResponse) Reset() {
	*x = SendPointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carsensor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPointResponse) ProtoMessage() {}

func (x *SendPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carsensor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPointResponse.ProtoReflect.Descriptor instead.
func (*SendPointResponse) Descriptor() ([]byte, []int) {
	return file_carsensor_proto_rawDescGZIP(), []int{1}
}

func (x *SendPointResponse) GetRoute() int32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *SendPointResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_carsensor_proto protoreflect.FileDescriptor

var file_carsensor_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x72, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x74, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x63, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x4a, 0x0a, 0x10, 0x43, 0x61,
	0x72, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36,
	0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x11, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x63, 0x61, 0x72, 0x73,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_carsensor_proto_rawDescOnce sync.Once
	file_carsensor_proto_rawDescData = file_carsensor_proto_rawDesc
)

func file_carsensor_proto_rawDescGZIP() []byte {
	file_carsensor_proto_rawDescOnce.Do(func() {
		file_carsensor_proto_rawDescData = protoimpl.X.CompressGZIP(file_carsensor_proto_rawDescData)
	})
	return file_carsensor_proto_rawDescData
}

var file_carsensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_carsensor_proto_goTypes = []interface{}{
	(*SendPointRequest)(nil),  // 0: SendPointRequest
	(*SendPointResponse)(nil), // 1: SendPointResponse
}
var file_carsensor_proto_depIdxs = []int32{
	0, // 0: CarSensorService.SendPoint:input_type -> SendPointRequest
	1, // 1: CarSensorService.SendPoint:output_type -> SendPointResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_carsensor_proto_init() }
func file_carsensor_proto_init() {
	if File_carsensor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_carsensor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carsensor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_carsensor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carsensor_proto_goTypes,
		DependencyIndexes: file_carsensor_proto_depIdxs,
		MessageInfos:      file_carsensor_proto_msgTypes,
	}.Build()
	File_carsensor_proto = out.File
	file_carsensor_proto_rawDesc = nil
	file_carsensor_proto_goTypes = nil
	file_carsensor_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CarSensorServiceClient is the client API for CarSensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarSensorServiceClient interface {
	SendPoint(ctx context.Context, opts ...grpc.CallOption) (CarSensorService_SendPointClient, error)
}

type carSensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarSensorServiceClient(cc grpc.ClientConnInterface) CarSensorServiceClient {
	return &carSensorServiceClient{cc}
}

func (c *carSensorServiceClient) SendPoint(ctx context.Context, opts ...grpc.CallOption) (CarSensorService_SendPointClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CarSensorService_serviceDesc.Streams[0], "/CarSensorService/SendPoint", opts...)
	if err != nil {
		return nil, err
	}
	x := &carSensorServiceSendPointClient{stream}
	return x, nil
}

type CarSensorService_SendPointClient interface {
	Send(*SendPointRequest) error
	CloseAndRecv() (*SendPointResponse, error)
	grpc.ClientStream
}

type carSensorServiceSendPointClient struct {
	grpc.ClientStream
}

func (x *carSensorServiceSendPointClient) Send(m *SendPointRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *carSensorServiceSendPointClient) CloseAndRecv() (*SendPointResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendPointResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CarSensorServiceServer is the server API for CarSensorService service.
type CarSensorServiceServer interface {
	SendPoint(CarSensorService_SendPointServer) error
}

// UnimplementedCarSensorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCarSensorServiceServer struct {
}

func (*UnimplementedCarSensorServiceServer) SendPoint(CarSensorService_SendPointServer) error {
	return status.Errorf(codes.Unimplemented, "method SendPoint not implemented")
}

func RegisterCarSensorServiceServer(s *grpc.Server, srv CarSensorServiceServer) {
	s.RegisterService(&_CarSensorService_serviceDesc, srv)
}

func _CarSensorService_SendPoint_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CarSensorServiceServer).SendPoint(&carSensorServiceSendPointServer{stream})
}

type CarSensorService_SendPointServer interface {
	SendAndClose(*SendPointResponse) error
	Recv() (*SendPointRequest, error)
	grpc.ServerStream
}

type carSensorServiceSendPointServer struct {
	grpc.ServerStream
}

func (x *carSensorServiceSendPointServer) SendAndClose(m *SendPointResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *carSensorServiceSendPointServer) Recv() (*SendPointRequest, error) {
	m := new(SendPointRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CarSensorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CarSensorService",
	HandlerType: (*CarSensorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendPoint",
			Handler:       _CarSensorService_SendPoint_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "carsensor.proto",
}
